# Generated by Django 4.1.7 on 2023-03-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(db_index=True, max_length=200)),
                ('image', models.ImageField(upload_to='lessons/')),
            ],
        ),
    ]
