# Generated by Django 4.1.7 on 2023-03-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(null=True, upload_to='lessons/video/'),
        ),
    ]
