# Generated by Django 4.1.7 on 2023-03-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='text',
        ),
    ]
